### ISSUE TITLE
receiver highlight not working

### ISSUE THREAD

**Issue by CaiJinKen** [charlespascoe/vim-go-syntax#12]
```vim
set termguicolors
colorscheme molokai
```

How amazing vim-go-syntax it is! Thanks authors!
But i found the receiver highlight only works on declear but not in function. I use coc.vim and theme is molokai.
The param l was not hightlighted. eg: 	if l.blockedUid == nil {

<img width="745" alt="image" src="https://github.com/user-attachments/assets/84b27bd3-1ffc-49a1-a40d-cf9869b20d89">

**Comment by charlespascoe** [comment]
Hi CaiJinKen! I'm glad to hear you like it, I've spent a lot of time working on it.

Unfortunately, Vim's syntax highlighting is purely lexical, meaning Vim uses the coding language's grammar to look for and highlight specific patterns in the text. This pattern-matching approach looks at the _structure_ of the code, but to do what you described would require understanding the semantic _meaning_ of the code.

Consider this example:

```go
type Foo struct {
	bar int
}

func (f Foo) Bar() int {
	if f := f.bar; f > 0 {
		return f
	}

	return 0
}
```

Here, the `f` in `f.bar` is referring to the receiver parameter, but the `f` in `f :=`, `f > 0`, and `return f` refers to a new variable that happens to have the same name. Although your code doesn't do this, the above example is still valid Go code, so I don't want my syntax definition to incorrectly highlight the new `f` variable as though it were the receiver, which would be confusing and misleading.

The reason the receiver parameter itself can be highlighted is because the grammar of Go dictates that in a top-level statement in the form `func (AAA BBB) CCC() {`, the text `AAA` is the receiver parameter name and `BBB` is the receiver parameter type, and so Vim can look for this pattern of text and highlight each part appropriately. However, in the statement `if A := B.C; A > 0 {`, there's nothing about this _pattern_ of text that indicates whether `B` is a receiver or some other variable; Vim would need to understand the _meaning_ of the code to determine whether `B` was a receiver parameter or not.

While the behaviour you described is technically possible using other text highlighting features in Vim, it is not trivial and would require relatively deep integration with the Go language server (`gopls`). At present, I'd rather keep this syntax definition relatively light and avoid adding lots of complexity and dependencies.

I hope this clarifies things!

**Comment by CaiJinKen** [comment]
The explanation is very detailed. Thank you very much!!!
