### ISSUE TITLE
syntax is cleared when switching colorscheme.

### ISSUE THREAD

**Issue by ghost** [charlespascoe/vim-go-syntax#2]
Is there anyway to prevent this when switching between colorschemes?

Another issue is if colorscheme is defined in vimrc and vimrc is sourced, syntax is cleared.

**Comment by charlespascoe** [comment]
Hi - sorry for the delay!

The reason this happens is because the setting the colorscheme clears the previous highlighting, including links between highlighting groups. Direct links to the "built-in" highlighting groups seem to be unaffected, but indirect links (i.e. element A should be highlighted like element B, and element B should be highlighted as a Statement) seem to be cleared. This isn't specific to this syntax definition - you may have noticed others have this issue as well, particularly more complex ones. Whenever I've encountered this, I usually just run `:e` which sources the syntax files again.

To automatically reload all syntax files, which will also set up all the highlighting links again, put the following autocommand in your `vimrc`:

```vim
colorscheme namehere

augroup ColourSchemeReload
    au!
    au ColorScheme * call <SID>FixSyntaxHighlightGroups()
augroup END

fun s:FixSyntaxHighlightGroups()
    let b = bufnr()
    let &l:filetype = &l:filetype
    bufdo let &l:filetype = &l:filetype
    exec "buffer" b
endfun
```

This sets the `filetype` option on every buffer every time the `colorscheme` command is run, which causes Vim to source all the necessary syntax files again. This will actually fix this issue for any filetype. It's best to make sure the `colorscheme` command is run _before_ the autocommand is registered, to avoid needlessly running this every time Vim opens.

Note that I've not tested this extensively, so there may be some odd behaviour - note that `bufdo` stops on the first error it encounters, which should be unlikely for the simple command it's doing.

I hope this helps :)
